# Generated by Django 3.0.6 on 2020-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidslapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestupdatesl',
            name='fatalityRate',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='latestupdatesl',
            name='recoveryRate',
            field=models.CharField(max_length=6),
        ),
    ]
