# Generated by Django 3.0.6 on 2020-05-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidslapi', '0002_auto_20200523_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='districtCases',
        ),
    ]
