# Generated by Django 3.0.6 on 2020-05-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidslapi', '0004_districtcases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='latestUpdateSl',
        ),
    ]
