# Generated by Django 3.0.6 on 2020-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidslapi', '0005_delete_latestupdatesl'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestUpdateSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedate', models.CharField(max_length=30)),
                ('updateTime', models.CharField(max_length=11)),
                ('newCases', models.CharField(max_length=3)),
                ('confirmedCases', models.CharField(max_length=5)),
                ('activeCases', models.CharField(max_length=5)),
                ('recoveredCases', models.CharField(max_length=5)),
                ('death', models.CharField(max_length=5)),
                ('recoveryRate', models.CharField(max_length=6)),
                ('fatalityRate', models.CharField(max_length=6)),
            ],
        ),
    ]
